## Compare Pivoting and Melting DataFrame

In [1]:
import pandas as pd

### Compare

In [6]:
shop_7Oct={
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[150,200,60,25],
    "Quantity":[15,7,12,13]
}
stock_7Oct=pd.DataFrame(shop_7Oct)

shop_8Oct={
    "Fruits":['Mango','Apple','Banana','Papaya'],
    "Price":[200,250,60,35],
    "Quantity":[10,17,24,15]
}
stock_8Oct=pd.DataFrame(shop_8Oct)

In [ ]:
stock_7Oct.compare(stock_8Oct)
stock_7Oct.compare(stock_8Oct, align_axis=0)
stock_7Oct.compare(stock_8Oct,keep_equal=True)
stock_7Oct.compare(stock_8Oct,keep_shape=True)
stock_7Oct.compare(stock_8Oct,keep_shape=True,keep_equal=True)

   Fruits         Price       Quantity
     self   other  self other     self other
0   Mango   Mango   150   200       15    10
1   Apple   Apple   200   250        7    17
2  Banana  Banana    60    60       12    24
3  Papaya  Papaya    25    35       13    15

### Pivoting

In [20]:
monthly_shop={
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":['Jan','Jan','Feb','Feb','Mar','Apr'],
    "Price":[50000,27500,65000,45000,95000,35000]
}
monthly_sales=pd.DataFrame(monthly_shop)
monthly_sales

monthly_sales.pivot(
    index="Product",
    columns="Month",
    values="Price"
)

Month        Apr      Feb      Jan      Mar
Product
Laptop   35000.0  65000.0  50000.0  95000.0
Mobile       NaN  45000.0  27500.0      NaN

In [21]:
monthly_shop={
    "Product":['Laptop','Mobile','Laptop','Mobile','Laptop','Laptop'],
    "Month":['Jan','Jan','Feb','Feb','Mar','Mar'],
    "Price":[50000,27500,65000,45000,95000,35000]
}
monthly_sales=pd.DataFrame(monthly_shop)
monthly_sales
monthly_sales.pivot_table(
    index="Product",
    columns="Month",
    values="Price",
    aggfunc="sum"
)

Month        Feb      Jan       Mar
Product
Laptop   65000.0  50000.0  130000.0
Mobile   45000.0  27500.0       NaN

### Melting

In [27]:
shop_sales={
    "Product":['Laptop','Mobile','Mouse'],
    "Jan":[67500,25000,950],
    "Feb":[87000,35000,850],
    "Mar":[98000,23500,650]
}
sales=pd.DataFrame(shop_sales)
sales.melt(
    id_vars="Product",
    var_name="Month",
    value_name="Sales"
)

  Product Month  Sales
0  Laptop   Jan  67500
1  Mobile   Jan  25000
2   Mouse   Jan    950
3  Laptop   Feb  87000
4  Mobile   Feb  35000
5   Mouse   Feb    850
6  Laptop   Mar  98000
7  Mobile   Mar  23500
8   Mouse   Mar    650